version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
      day: "monday"
    labels:
      - "npm dependencies"
